spring:
  application:
    name: web-java
  threads:
    virtual:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?options=-csearch_path=public
    username: postgres
    password: 12345678
    hikari:
      maximum-pool-size: 200

server:
  port: 3000